const fs = require('fs')

fs.writeFileSync('courseNotes.txt',"Many times, you will want to run code asynchronously so your program doesn't pause.\n")
fs.appendFileSync('courseNotes.txt',"This is especially true when your program needs to get data from a database or maybe an api or http request.\n")
fs.appendFileSync('courseNotes.txt',"JS is normally rund synchronosly so line by line in the order it is written. \n\n")
fs.appendFileSync('courseNotes.txt',"Asynchronous coding is accomplished through callback functions. The callback queue is called after the call stack completes\n")
fs.appendFileSync('courseNotes.txt',"This allows the program to continue running while the callback function gets the data. Once the stack is done, the callback \n")
fs.appendFileSync('courseNotes.txt',"queue will run which then returns the data that was requested earlier in the program\n")
fs.appendFileSync('courseNotes.txt',"\n")
fs.appendFileSync('courseNotes.txt',"\n")
