const fs = require('fs');

fs.writeFileSync('courseNotes.txt', "The module file system is assigned to the variable fs -> 'const fs = require('fs')'"+'\n\n');
fs.appendFileSync('courseNotes.txt',"fs.writeFileSync('file.name', 'data to write') creates or overwrites that file\n\n");
fs.appendFileSync('courseNotes.txt',"fs.appendFileSync('file.name', 'data to write') adds data to the end of that file\n\n");
fs.appendFileSync('courseNotes.txt',"adding \\n at the end of the data causes the next addition on a new line\n\n");
fs.appendFileSync('courseNotes.txt',"You can link to your own files by providing the relative path ie. require()./fileName.js\n\n");
fs.appendFileSync('courseNotes.txt',"Each individual file has it's own scope so variables do not cross file bounderies\n\n");
fs.appendFileSync('courseNotes.txt',"You can 'explicitly' export variables from one file to another via module.exports = variable in the sending file\n\n");
fs.appendFileSync('courseNotes.txt',"To use the data from module.exports, the receiving file must have const variable = require('relative path to exporting file')\n\n");
fs.appendFileSync('courseNotes.txt',"npm init in the root on the terminal is used to add the node package manager (package.json) file to the project\n\n");
fs.appendFileSync('courseNotes.txt',"npm packages can be found and npmjs.com and will have an install command to copy. Paste in terminal root.\n\n");
fs.appendFileSync('courseNotes.txt',"The install command will add a node_modules folder and a package-lock.json file (do not edit thes) \n\n");
fs.appendFileSync('courseNotes.txt',"This will also add the package you are installing as a dependency in package.json\n\n");
fs.appendFileSync('courseNotes.txt',"To use the new package, add const variable = require('packageName') in the main application file\n\n");
fs.appendFileSync('courseNotes.txt',"The node-modules folder can be deleted and ignored and can (and should) be recreated on every computer it is downloaded to.\n");
fs.appendFileSync('courseNotes.txt',"Do this by running npm install at the terminal root (info needed automatically comes from package and package-lock files.\n\n");
fs.appendFileSync('courseNotes.txt',"You will want to install some npm packages globally. This is done with the -g flag at the end of the install command.\n\n");
fs.appendFileSync('courseNotes.txt',"nodemon is an example of a globally installed package and it will automatically run the code every time you save a file.\n\n");
fs.appendFileSync('courseNotes.txt',"nodemon will not show up on package-lock or package files in the project.\n\n");
fs.appendFileSync('courseNotes.txt',"start nodemon on a file by typing nodemon fileName.js in terminal. Quit nodemon with ctrl Q in terminal.\n\n");
fs.appendFileSync('courseNotes.txt',"\n\n");
fs.appendFileSync('courseNotes.txt',"\n\n");
